### ISSUE TITLE
Update README.md instruction

### ISSUE THREAD

**Issue by datlife** [tonyghita/graphql-go-example#4]
Hi @tonyghita,

Thank you for your great work! I wonder if you could clarify or need a hand to update README for how to get this example up and running, as I am trying to do it right now. However, there is some issue during the compilation that I might need your help

**Build System** : Ubuntu 18.04 (Linux x86_64)
**What I have done**:
* Cloned this repo.
* Installed dependencies (`dep`, `go-bindata`) under `/home/$USER/go`.
* Add the parent dir `example` of this repo to `GOPATH`:
```shell
# cd example
# export GOPATH=$GOPATH:$(pwd)
example
└── src
    └── graphql-go-example
``` 

**Issue**:

* When I ran `make server`, it throws me this error:
```shell
dat@laptop:~/Documents/example/src/graphql-go-example$ make server

▶ Fetching github.com/golang/dep...
go get github.com/golang/dep/cmd/dep
▶ Ensuring vendored dependencies are up-to-date...
dep ensure
▶ Embedding schema files into binary...
go generate ./schema
▶ Starting development server...
go run server.go
# graphql-go-example/vendor/github.com/tonyghita/graphql-go-example/schema
vendor/github.com/tonyghita/graphql-go-example/schema/schema.go:21:23: undefined: AssetNames
vendor/github.com/tonyghita/graphql-go-example/schema/schema.go:22:8: undefined: MustAsset
Makefile:18: recipe for target 'server' failed
make: *** [server] Error 2
```

I am not sure how to deal with this as I am fairly new to both Golang and GraphQL. Any pointer would be greatly appreciated!

Regards,
Dat

**Comment by moyuanhuang** [comment]
@datlife 
I had to manually `cp ./schema/bindata.go ./vendor/github.com/tonyghita/graphql-go-example/schema`, since it tries to find the two functions in the vendor dir but somehow it's not there after generating the `bindata.go` in `./schema`. After this you need to directly run `go run server.go` instead `make server`, since it will 'rebuilts' the verdor directory again.

I don't know how to properly move it to the vendor directory tho.😨

**Comment by tonyghita** [comment]
This project isn't really meant to be vendored, but to be run as a standalone application. I think that mismatch of expectations is what is causing these issues.

I'm curious to know more about how you're expecting this example project to be used.

**Comment by moyuanhuang** [comment]
From my perspective, this app's functionality is exactly what I wanted. I'm trying to build a server similar to this, simply just setting the application up running and playing around a little bit is extremely helpful to me. So a big Thanks to @tonyghita! 

I'm relatively new to go and totally new to graphql, but after spending ~8h on this repo, I understood
1. how to use [dep](https://github.com/golang/dep)
2. how to use [bindata](https://github.com/jteeuwen/go-bindata)
3. what is graphql and why it is popular
4. how graphql and go are together and how we could approach it

Meanwhile, it'll be awesome if this project can explain a little bit more about **1** and **2**(such as the #TODO in `schema.go`) in README. This can help people set up the application much easier.

**Comment by bsr203** [comment]
@tonyghita Can you please comment on rationale of embedding the binary instead of using the string! thanks

**Comment by tonyghita** [comment]
@bsr203 imagine you have hundreds of types in your production system. It'd be pretty hard to manage one large string, no?

Keeping the SDL files separate is nice because we get 1. syntax highlighting in IDEs 2. a separation of concerns. 

Embedding the SDL files in the binary keeps deploying the application easy since we don't have to ship the SDL files separately.

**Comment by bsr203** [comment]
Thanks Tony for the response. It perfectly makes sense and your project is a great is a great reference. thanks again.

**Comment by u007** [comment]
even after go generate ./schema/ , im still getting
```
undefined: MustAsset
```
but i did **not** get
```
undefined: AssetNames
```

**Comment by mailtruck** [comment]
I had to install go-bindata:

```
go get -u github.com/jteeuwen/go-bindata/...
```

**Comment by tonyghita** [comment]
I revisited this codebase to remove those external dependencies now that Go 1.16 has introduced the `embed` package and we're using modules for dependency management, and updated the README and Makefile to reflect these changes.

Related commit is 883556b613167f5846dabaa748db5ec4b430164d.
