### ISSUE TITLE
Problem with go-generate

### ISSUE THREAD

**Issue by theoks** [tonyghita/graphql-go-example#5]
I have used the pattern in the schema folder, where I break the graphql files and use the `go-generate` library to create assets prior to build. However even without changing the `bindata.go` file it seems that the assets are most probably not generated correctly, since I get the following error:

`"Cannot query field \"findUser\" on type \"Query\"."` (where "findUser" a query)

When this happens I have to regenerate the file, but even then it doesn't always work. Is there another alternative to `go-generate`?

**Comment by cpunekar** [comment]
Hello @theoks, were you able to use `go-generate` successfully?

**Comment by tonyghita** [comment]
I updated this project to use the new `embed` package introduced in Go 1.16 which should resolve the issue with the external dependency. Commit that fixes this: 36fbf89b05f1609c727c1984a54e78228ee1c6a0
