### ISSUE TITLE
Question: Why not pass mux straight into ListenAndServe?

### ISSUE THREAD

**Issue by crung** [tonyghita/graphql-go-example#6]
Have mercy on me for I am a newbie.

I've been studying Go over the last few days and grokked the language tour etc. I wanted to know, out of curiosity, why you don't pass mux straight into ListenAndServe? I haven't found anything discussing this on google so far. My assumption is that you wanted fine grain control over the configuration of the server?

Thanks,

James.

**Comment by crung** [comment]
Found a bit more detail: https://golang.org/pkg/net/http

I suppose my question should relate to why you use those particular settings.

**Comment by tonyghita** [comment]
The http server settings aren't particularly well tuned. You'll definitely want to choose something that makes sense for your production workload.

Filippo Valsorda wrote a great blog post about some of the timeout components that should be set if you're exposing your server to the internet: 

- https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
- https://blog.cloudflare.com/exposing-go-on-the-internet/
