### ISSUE TITLE
Explanation for certain design choices

### ISSUE THREAD

**Issue by MDanialSaleem** [tonyghita/graphql-go-example#7]
Hey,

This has been puzzling me. Could you please complete this todo ?

https://github.com/tonyghita/graphql-go-example/blob/b146e697830582faa49e95e906c5a562ffa37aa8/schema/schema.go#L1

Thanks!

**Comment by tonyghita** [comment]
I've expanded the documentation for the schema packaging component.

https://github.com/tonyghita/graphql-go-example/blob/6f783a33be60f61a6e2fdf0ac966866dfb9c3890/schema/schema.go#L1-L15

Let me know if this helps.
